version: 2
updates:
  - package-ecosystem: "<ecosystem>"  # Replace with your package manager (e.g., "npm", "pip", "cargo")
    directory: "<directory>"           # Optional: Directory containing dependencies (defaults to project root)
    # Additional options (refer to Dependabot documentation for details):
    # - ranges: ...
    # - schedule: ...
    # - ignore-dependencies: ...
    # - labels: ...
